apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-tekton-argo
spec:
  params:
    - default: sample-app-2
      name: APP_NAME
      type: string
    - default: 'https://github.com/rawatsunildun/movielisting'
      name: GIT_REPO
      type: string
    - name: GIT_REVISION
      type: string
    - default: quay.io/rawatsunil3677/movie-listing
      name: IMAGE_NAME
      type: string
    - default: movielisting
      name: PATH_CONTEXT
      type: string
    - default: 6.0-ubi8
      name: VERSION
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: s2i-dotnet
      workspaces:
        - name: source
          workspace: workspace
    - name: git-update-deployment
      params:
        - name: GIT_PROJECT
          value: gitops-repo-moivelisting
        - name: GIT_REPOSITORY
          value: 'https://github.com/rawatsunildun/gitops-repo-moivelisting'
        - name: GIT_USERNAME
          value: rawatsunildun
        - name: GIT_PASSWORD
          value: >-
            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
        - name: CURRENT_IMAGE
          value: dotnet-6.0
        - name: NEW_IMAGE
          value: quay.io/rawatsunil3677/movie-listing
        - name: NEW_DIGEST
          value: $(tasks.build.results.IMAGE_DIGEST)
        - name: KUSTOMIZATION_PATH
          value: environment/dev
      runAfter:
        - build
      taskRef:
        kind: Task
        name: git-update-deployment
      workspaces:
        - name: workspace
          workspace: workspace
  workspaces:
    - name: workspace
