apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: 1.0
  name: dotnet-6.0
  newName: image-registry.openshift-image-registry.svc:5000/dotnet-myapp/sample-app-2
