apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:920985b142a3a2ba97194f0ddb7bcab43498de9b5ff3631f0cf4e6ecc174abea
  name: dotnet-6.0
  newName: quay.io/narendragomte/sample-app
