apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:4d359380e3b5d3cca7547869c1ada878074c8137252d9422ac5ff2c16fa80365
  name: dotnet-6.0
  newName: quay.io/rawatsunil3677/movie-listing
