kind: Deployment
apiVersion: apps/v1
metadata:
  name: movielisting
  labels:
    app: movielisting
    app.kubernetes.io/component: movielisting
    app.kubernetes.io/instance: movielisting
    app.kubernetes.io/name: movielisting
    app.kubernetes.io/part-of: dotnetcore-movielisting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movielisting
  template:
    metadata:
      labels:
        app: movielisting
        deploymentconfig: movielisting
    spec:
      containers:
        - name: movielisting
          image: dotnet-6.0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
